workflows:
  telegram-bot:
    name: Run Bot with C++11 Program

    environment:
      docker_image: python:3.10

    scripts:
      - echo "ULTRA BHAI BOT START..."

      # System update
      - apt-get update

      # Install g++
      - apt-get install -y g++

      # Python setup
      - pip install --upgrade pip
      - pip install pyTelegramBotAPI pymongo aiohttp psutil pytz

      # Compile C++ (your command)
      - echo "Compiling soul.cpp..."
      - g++ -std=c++11 -pthread -o soul soul.cpp

      # Permission
      - chmod +x soul

      # Debug check
      - ls -la

      # Run Python bot
      - python3 ultra.py
