workflows:
  telegram-bot:
    name: Run Bot

    scripts:
      - echo "ULTRA BHAI BOT START..."

      # Python setup
      - pip3 install --upgrade pip
      - pip3 install pyTelegramBotAPI pymongo aiohttp psutil pytz

      # Compile C++
      - g++ -std=c++14 -pthread -o soul soul.cpp

      # Permission
      - chmod +x soul

      # Run bot
      - python3 soul.py
